- .eslintrc.json
- package-lock.json
- package.json
- packages/core/classes/manager/__test__/entity-manager.spec.ts
- packages/core/classes/manager/entity-manager.ts
Include all autogenerated attributes when returning created item
closes #11
> 11 missing attributes on entity manager create operation

- packages/core/public-api.ts
- packages/core/src/classes/connection/__test__/connection-manager.spec.ts
- packages/core/src/classes/connection/connection-manager.ts
- packages/core/src/classes/connection/connection.ts
> fix(core): connection manager not cleaning up broken connections

- packages/core/src/classes/__test__/expression-builder.spec.ts
- packages/core/src/classes/expression-builder.ts
- Allows updating attribute with undefined values 
closes #41
> fix(core): allow updating attributes with undefined value

- packages/common/src/metadata/metadata-storage.ts
- packages/common/src/utils/__test__/get-entity-definition.spec.ts
- packages/common/src/utils/get-entity-definition.ts
> feat(common): add helper to get entity definition

- packages/common/src/decorators/attribute.decorator.ts
- packages/common/src/error/attribute-metadata-unsupported-default-value-error.ts
- packages/common/src/error/index.ts
- packages/common/src/metadata/metadata-storage.ts
- packages/core/src/classes/metadata/__test__/attribute-metadata.spec.ts
- packages/core/src/classes/metadata/attribute-metadata.ts
- packages/core/src/classes/transformer/__test__/dc-request-transformer.spec.ts
- packages/core/src/classes/transformer/document-client-request-transformer.ts
- packages/core/src/helpers/__test__/get-dynamo-query-limit.spec.ts
- packages/core/src/helpers/is-scalar-type.ts
- add support for specifying default values on attribute
closes #12
> 12 support specifying default value for attribute

- packages/common/src/error/index.ts
- packages/common/src/error/missing-required-table-config.ts
- packages/core/src/classes/connection/__test__/entity-metadata-builder.spec.ts
- packages/core/src/classes/connection/connection.ts
- packages/core/src/classes/connection/entity-metadata-builder.ts
> fix(core): Misleading error when missing required table config

- packages/core/src/classes/expression/__test__/base-expression-input.spec.ts
- packages/core/src/classes/expression/base-expression-input.ts
- packages/core/src/classes/manager/__test__/entity-manager.spec.ts
- fixes expression evaluation order issue
closes #75
> fix(core): wrong expression nesting with filter expressions

- packages/common/package.json
> fix(common): remove circular peer dep

- packages/core/src/classes/expression/__test__/expression-builder.spec.ts
- packages/core/src/classes/expression/__test__/expression-input-parser.spec.ts
- packages/core/src/classes/expression/__test__/remove-update.spec.ts
- packages/core/src/classes/expression/base-expression-input.ts
- packages/core/src/classes/expression/expression-input-parser.ts
- packages/core/src/helpers/constants.ts
- fix expression input parser to correctly build expressions for nested attr references
closes #139
> fix expression input parser

- packages/common/public-api.ts
- packages/common/src/helpers/resolve-scalar-type.ts
- packages/core/src/classes/expression/__test__/expression-input-parser.spec.ts
- packages/core/src/classes/expression/condition-options-type.ts
- packages/core/src/classes/expression/filter-options-type.ts
> fix(core): in filter and condition expression, correctly infer value types

- packages/core/src/classes/expression/expression-input-parser.ts
- packages/core/src/classes/transformer/__test__/dc-request-transformer.spec.ts
> fix(core): update item with custom transforms

- __test__/__mocks__/test-table.ts
- __test__/github-issues/152/issue-152.spec.ts
- __test__/github-issues/152/test-entity.ts
> test(github-issues): add tests for #152

- __test__/github-issues/184/issue-184.spec.ts
- __test__/github-issues/184/specific-event-entity.ts
> Add tests for #184

- package.json
> fix(core): lock class-transformer dep to 0.4.0

- packages/common/package.json
- packages/core/package.json
> Lock class-transformer dep to 0.4.0

- README.md
- docs/api.md
- docs/upgrading-to-use-the-aws-sdk-v3.md
- packages/document-client/README.md
- packages/document-client/package.json
- packages/document-client/src/classes/document-client-v2.ts
- packages/document-client/src/classes/document-client-v3.ts
- packages/document-client/src/exceptions/transaction-cancelled-exception.ts
> Add AWS SDK V3 upgrade notes

- __test__/github-issues/194/issue-194.spec.ts
- __test__/github-issues/194/tenant-entity.ts
- docs/how-to-recipes.md
- packages/common/src/decorators/attribute.decorator.ts
- packages/common/src/metadata/metadata-storage.ts
- packages/core/src/helpers/build-primary-key-schema.ts
> [#194] Update type definition for attribute aliasing

- .vscode/settings.json
- __test__/github-issues/157/issue-157.spec.ts
- docs/api.md
- packages/core/src/classes/manager/__test__/entity-manager.spec.ts
- packages/core/src/classes/manager/entity-manager.ts
- packages/core/src/classes/transformer/__test__/dc-request-transformer.spec.ts
- packages/core/src/classes/transformer/document-client-request-transformer.ts
> [#198] strong consistent read support

- packages/testing/index.ts
> [#252] add AWS SDK v3 support  support to testing lib

- docs/guide.md
it ain't much, but it's honest work
> fix: updates a typo in guide of docs
